mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=banco

smallrye.jwt.sign.key.location=privateKey.pem

quarkus.smallrye-jwt.enabled=true

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5434/seubanco
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

quarkus.hibernate-orm.database.generation=update

quarkus.log.category."io.smallrye.jwt".level=DEBUG