# Configuração do Banco de Dados PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=katia
quarkus.datasource.password=123456

# O nome do banco deve ser api_bancaria (com underline, conforme o teu psql)
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/api_bancaria

# Configuração do Hibernate (Panache)
# 'none' evita que o Hibernate tente criar tabelas que já existem
quarkus.hibernate-orm.database.generation=none

# Mostra o SQL no terminal para sabermos o que o Java está a fazer
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=no-file

# Ajuste para evitar erros de serialização de JSON
quarkus.jackson.serialization-features.fail-on-empty-beans=false

# Porta padrão da API
quarkus.http.port=8080