# -----------------------------------------------------------
# 1. BANCO DE DADOS (H2 Permanente em Arquivo)
# -----------------------------------------------------------
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:C:/temp/bancada;DB_CLOSE_DELAY=-1

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# ---------------------------------------------------------------
# JWT - Segurança da Bancada da Katia
# ---------------------------------------------------------------
quarkus.smallrye-jwt.enabled=true

# Ajustado para o SEU projeto
mp.jwt.verify.issuer=https://br.com.katia.banco/issuer

# Aponta para os arquivos que você salvou em src/main/resources
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
# 3. CONTROLE DE ACESSO (Permissões Públicas)
# -----------------------------------------------------------
quarkus.http.auth.permission.publico.paths=/clientes,/auth/login
quarkus.http.auth.permission.publico.policy=permit
quarkus.http.auth.permission.publico.methods=GET,POST